config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  root 'home#index'
  get 'orders', to: 'home#orders'

  namespace :admin do
    resources :dashboard, only: :index
    resources :products
    resources :categories
  end

  resources :products, only: :show
  
  scope '/checkout' do
  	post 'create', to: 'checkout#create', as: 'checkout_create'
  	get 'success', to: 'checkout#success', as: 'checkout_success'
  	get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  end

  resource :cart, only: :show
  resources :order_products, only: %i[create update destroy]

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  belongs_to :user
  has_many :order_products
  has_many :products, through: :order_products

  before_save :set_total

  def total
  	order_products.collect {|order_product| order_product.valid? ? (order_product.unit_price*order_product.quantity) : 0}.sum
  end

  def total_in_cent
  	(self.total*100).to_i
  end


  private

  def set_total
  	self[:total] = total
  end
end

app/models/order_product.rb
# frozen_string_literal: true

class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product

  before_save :set_unit_price
  before_save :set_total_price
  
  def unit_price
  	if persisted?
  		self[:unit_price]
  	else
  		product.price
  	end
  end

  def total_price
  	quantity * unit_price
  end


  private

  def set_unit_price
  	self[:unit_price] = unit_price
  end

  def set_total_price
  	self[:total_price] = quantity * set_unit_price
  end
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord

	before_validation :set_slug, on: [:create, :update]

  has_many :order_products
  has_many :orders, through: :order_products

  has_one_attached :image

  belongs_to :category

  validates_presence_of :slug

  def self.popular
 		ordered_products = Product.joins(:order_products).group(:id)
 		ordered_products_sum = ordered_products.sum(:quantity)
 		ordered_products_quantities = ordered_products_sum.map{|k,v| v}
 		ordered_products.enum_for(:each_with_index)
 			.map{|e,i|
 				{
 					title: e[:title],
 					price: e[:price],
 					quantity: ordered_products_quantities[i],
 					total: e[:price]*ordered_products_quantities[i]
 				}
 			}
 		.take(5)
  end

	def to_param
		slug
	end


	private

	def set_slug
		self.slug = title.parameterize
	end

end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :orders

  after_create :welcome_email

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def welcome_email
  	UserMailer.with(user: self).welcome_email.deliver_now
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  def index
  	@customers = User.where(admin: false).count
  	@orders = Order.where(paid: true)
  	@order_count = @orders.count
  	@revenue = @orders.pluck(:total)
  	@total_sales = @revenue.sum
  	@average_sale_size = 
  		@total_sales>0 ? @total_sales/@revenue.size : 0
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include ApplicationHelper
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

class CartsController < ApplicationController
  def show
  	@order = current_order
    @order_products = @order.order_products
  end
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  def create
  	order = current_order

  	@session = Stripe::Checkout::Session.create(
  		payment_method_types: ['card'],
  		line_items: [{
  			name: 'Eshop products',
  			description: "payment of order : #{order.id}",
  			amount: order.total_in_cent,
  			currency: 'eur',
  			quantity: 1,
			}],
      success_url: checkout_success_url,
      cancel_url: checkout_cancel_url,
  	)

  	respond_to do |format|
  		format.js
  	end
  end

  def success
    order = current_order
    order.update_attribute(:paid, true)
    @order_products = order.order_products
    cookies.delete(:cart)
    UserMailer.with(user: current_user).order_email.deliver_now
    UserMailer.with(admin: User.find_by(admin: true)).admin_order_email.deliver_now
  end

  def cancel
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @categories = Category.all
    category = params[:category]
    if !!category
    	@products = Product.where(category: category)
    else
    	@products = Product.all
    end
    @order_product = current_order.order_products.new
  end

  def orders
  	@orders = Order.where(user: current_user, paid: true).includes(:products)
  end
end

app/controllers/order_products_controller.rb
# frozen_string_literal: true

class OrderProductsController < ApplicationController
  before_action :set_order
  before_action :set_product, only: [:update, :destroy]
  
  def create
    @order_product = @order.order_products.new(order_item_params)
    @order.save
    cookies[:cart] = @order.id
  end

  def update
    @order_product.update_attributes(order_item_params)
    redirect_to cart_path
  end

  def destroy
    @order_product.destroy
    redirect_to cart_path
  end

  private

  def set_order
    @order = current_order
  end

  def set_product
    @order_product = @order.order_products.find(params[:id])
  end

  def order_item_params
    params.require(:order_product).permit(:product_id, :quantity)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def show
  	@product = Product.find_by_slug(params[:id])
  	@products = Product.all.sample(4)
  	@order_product = current_order.order_products.new
  end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
	def authenticate_admin
		redirect_to root_path if !current_user.admin
	end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def current_order
    if !!cookies[:cart]
      Order.find(cookies[:cart])
    else
      Order.new(user: current_user)
    end
  end
end

app/helpers/carts_helper.rb
# frozen_string_literal: true

module CartsHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/order_products_helper.rb
# frozen_string_literal: true

module OrderProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/dashboard/index.html.erb
<%= render partial: 'layouts/banner', locals: { page: 'Dashboard', information: 'Welcome' } %>
<div class="container">
    <div class="content-page">
        
        <div class="content">

            <div class="container-fluid">

                <div class="row mt-3">

                    <div class="col-lg-3">

                        <div data-toggle="sticky" data-sticky-offset="100" data-negative-margin=".card-profile-cover">

                            <div class="card">
                                <div class="card-header py-3">
                                    <i class="fas fa-tasks mr-2"></i>
                                    <span class="h6">Manage</span>
                                </div>
                                <div class="list-group list-group-sm list-group-flush">
                                    <%= link_to "Products", admin_products_path, class: 'list-group-item list-group-item-action d-flex justify-content-between' %>
                                    <%= link_to "Categories", admin_categories_path, class: 'list-group-item list-group-item-action d-flex justify-content-between' %>
                                </div>
                            </div>

                        </div>

                    </div>


                    <div class="col-lg-9">

                        <div class="row mb-2">
                            <div class="col-lg-6">
                                <div class="card widget-flat">
                                    <div class="card-body">
                                        <div class="float-right">
                                            <%= @customers %> <i class="fas fa-user-friends"></i>
                                        </div>
                                        <h5 class="text-muted font-weight-normal mt-0" title="Number of Customers">Customers</h5>
                                    </div>
                                </div>
                            </div>

                            <div class="col-lg-6">
                                <div class="card widget-flat">
                                    <div class="card-body">
                                        <div class="float-right">
                                            <%= @order_count %> <i class="fas fa-cart-plus"></i>
                                        </div>
                                        <h5 class="text-muted font-weight-normal mt-0" title="Number of Orders">Orders</h5>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row mb-2">
                            <div class="col-lg-6">
                                <div class="card">
                                    <div class="card-body">
                                        <h4 class="header-title mb-4">Total Sales</h4>
                                        <div class="text-center">
                                            <h3 class="font-weight-normal text-primary mb-2"><%= @total_sales.to_s(:currency) %></h3>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="col-lg-6">
                                <div class="card bg-primary">
                                    <div class="card-body">
                                        <h4 class="header-title text-white mb-4">Average Sale Size</h4>
                                        <div class="text-center">
                                            <h3 class="font-weight-normal text-white mb-2">$<%= @average_sale_size %></h3>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="col-lg-12 mt-3">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="header-title mt-2">Top Selling Products</h4>
                                
                                <div class="table-responsive">
                                    <% Product.popular.each do |product| %>
                                        <table class="table table-centered table-hover mb-0">
                                            <tbody>
                                                <tr>
                                                    <td>
                                                        <h5 class="font-14 mb-1 font-weight-normal"><%= product[:title] %></h5>
                                                    </td>
                                                    <td>
                                                        <h5 class="font-14 mb-1 font-weight-normal">$<%= product[:price] %></h5>
                                                        <span class="text-muted font-13">Price</span>
                                                    </td>
                                                    <td>
                                                        <h5 class="font-14 mb-1 font-weight-normal"><%= product[:quantity] %></h5>
                                                        <span class="text-muted font-13">Quantity</span>
                                                    </td>
                                                    <td>
                                                        <h5 class="font-14 mb-1 font-weight-normal">$<%= product[:total] %></h5>
                                                        <span class="text-muted font-13">Amount</span>
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    <% end %>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>