config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  root 'home#index'
  get 'orders', to: 'home#orders'

  namespace :admin do
    resources :dashboard, only: :index
    resources :products
    resources :categories
  end

  resources :products, only: :show
  
  scope '/checkout' do
  	post 'create', to: 'checkout#create', as: 'checkout_create'
  	get 'success', to: 'checkout#success', as: 'checkout_success'
  	get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  end

  resource :cart, only: :show
  resources :order_products, only: %i[create update destroy]

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  belongs_to :user
  has_many :order_products
  has_many :products, through: :order_products

  before_save :set_total

  def total
  	order_products.collect {|order_product| order_product.valid? ? (order_product.unit_price*order_product.quantity) : 0}.sum
  end

  def total_in_cent
  	(self.total*100).to_i
  end


  private

  def set_total
  	self[:total] = total
  end
end

app/models/order_product.rb
# frozen_string_literal: true

class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product

  before_save :set_unit_price
  before_save :set_total_price
  
  def unit_price
  	if persisted?
  		self[:unit_price]
  	else
  		product.price
  	end
  end

  def total_price
  	quantity * unit_price
  end


  private

  def set_unit_price
  	self[:unit_price] = unit_price
  end

  def set_total_price
  	self[:total_price] = quantity * set_unit_price
  end
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord

	before_validation :set_slug, on: [:create, :update]

  has_many :order_products
  has_many :orders, through: :order_products

  has_one_attached :image

  belongs_to :category

  validates_presence_of :slug

  def self.popular
 		ordered_products = Product.joins(:order_products).group(:id)
 		ordered_products_sum = ordered_products.sum(:quantity)
 		ordered_products_quantities = ordered_products_sum.map{|k,v| v}
 		ordered_products.enum_for(:each_with_index)
 			.map{|e,i|
 				{
 					title: e[:title],
 					price: e[:price],
 					quantity: ordered_products_quantities[i],
 					total: e[:price]*ordered_products_quantities[i]
 				}
 			}
 		.take(5)
  end

	def to_param
		slug
	end


	private

	def set_slug
		self.slug = title.parameterize
	end

end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :orders

  after_create :welcome_email

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def welcome_email
  	UserMailer.with(user: self).welcome_email.deliver_now
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
	include Admin::ProductsHelper
	before_action :authenticate_admin
	before_action :set_product, only: [:show, :edit, :update, :destroy]

	def index
		@products = Product.includes(:category).all
	end

	def show
	end

	def new
		@product = Product.new
	end

	def create
		@product = Product.create(product_params)
		if @product.save
			redirect_to @product
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @product.update(product_params)
			redirect_to @product
		else
			render 'edit'
		end
	end

	def destroy
		@product.destroy
		redirect_to admin_products_path
	end


	private

	def set_product
		@product = Product.find_by_slug(params[:id])
	end

	def product_params
		params.require(:product).permit(:title, :description, :price, :image, :category_id)
	end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include ApplicationHelper
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

class CartsController < ApplicationController
  def show
  	@order = current_order
    @order_products = @order.order_products
  end
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  def create
  	order = current_order

  	@session = Stripe::Checkout::Session.create(
  		payment_method_types: ['card'],
  		line_items: [{
  			name: 'Eshop products',
  			description: "payment of order : #{order.id}",
  			amount: order.total_in_cent,
  			currency: 'eur',
  			quantity: 1,
			}],
      success_url: checkout_success_url,
      cancel_url: checkout_cancel_url,
  	)

  	respond_to do |format|
  		format.js
  	end
  end

  def success
    order = current_order
    order.update_attribute(:paid, true)
    @order_products = order.order_products
    cookies.delete(:cart)
    UserMailer.with(user: current_user).order_email.deliver_now
    UserMailer.with(admin: User.find_by(admin: true)).admin_order_email.deliver_now
  end

  def cancel
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @categories = Category.all
    category = params[:category]
    if !!category
    	@products = Product.where(category: category)
    else
    	@products = Product.all
    end
    @order_product = current_order.order_products.new
  end

  def orders
  	@orders = Order.where(user: current_user, paid: true).includes(:products)
  end
end

app/controllers/order_products_controller.rb
# frozen_string_literal: true

class OrderProductsController < ApplicationController
  before_action :set_order
  before_action :set_product, only: [:update, :destroy]
  
  def create
    @order_product = @order.order_products.new(order_item_params)
    @order.save
    cookies[:cart] = @order.id
  end

  def update
    @order_product.update_attributes(order_item_params)
    redirect_to cart_path
  end

  def destroy
    @order_product.destroy
    redirect_to cart_path
  end

  private

  def set_order
    @order = current_order
  end

  def set_product
    @order_product = @order.order_products.find(params[:id])
  end

  def order_item_params
    params.require(:order_product).permit(:product_id, :quantity)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def show
  	@product = Product.find_by_slug(params[:id])
  	@products = Product.all.sample(4)
  	@order_product = current_order.order_products.new
  end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
	def authenticate_admin
		redirect_to root_path if !current_user.admin
	end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def current_order
    if !!cookies[:cart]
      Order.find(cookies[:cart])
    else
      Order.new(user: current_user)
    end
  end
end

app/helpers/carts_helper.rb
# frozen_string_literal: true

module CartsHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/order_products_helper.rb
# frozen_string_literal: true

module OrderProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/_cart.html.erb
<%= render partial: 'layouts/banner', locals: { page: 'Shopping Cart', information: 'Cart information' } %>

<section class="slice slice-lg">
    <div class="container">
        <!-- Shopping cart -->
        <div class="table-responsive">
            <table class="table align-items-center">
                <thead>
                    <tr>
                        <th>Product</th>
                        <th>Unit price</th>
                        <th>Quantity</th>
                        <th>Total</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>

                    <% @order_products.each do |order_product| %>
                        <tr>
                            <td>
                                <div class="media align-items-center">
                                    <%= image_tag order_product.product.image, alt: 'Image placeholder', width: '80', class: 'mr-3' %>
                                    <div class="media-body">
                                        <div class="lh-100">
                                            <span class="text-dark font-weight-bold mb-0"><%= order_product.product.title %></span>
                                        </div>
                                        <span class="font-weight-bold text-muted"><%= order_product.product.description %></span>
                                    </div>
                                </div>
                            </td>
                            <td>
                                <span class="font-weight-bold"><%= order_product.unit_price %> &euro;</span>
                            </td>
                            <td>
                                <%= form_with model: order_product, url: order_product_path(order_product), method: :put do |f| %>
                                    <div class="row">
                                        <%= f.hidden_field :product_id, value: order_product.product.id %>
                                        <%= f.text_field :quantity, value: order_product.quantity, min: 1, class: 'form-control form-control-sm text-center', style: 'width: 80px' %>
                                        <%= f.submit 'Update', class: 'btn btn-sm btn-primary ml-1' %>
                                    </div>
                                    
                                <% end %>
                            </td>
                            <td>
                                <span class="font-weight-bold text-dark"><%= order_product.total_price %> &euro;</span>
                            </td>
                            <td class="text-right">
                                <%= link_to '<i class="fas fa-trash-alt"></i>'.html_safe, order_product_path(order_product), class: 'text-light', method: :delete, data: { confirm: 'Are you sure?', toggle: 'tooltip', original: {title: 'Remove item'} } %>
                            </td>
                        </tr>
                    <% end %>

                </tbody>
            </table>
        </div>

        <!-- Cart information -->
        <div class="mt-5 pt-5 delimiter-top">
            <div class="row justify-content-center">
                <div class="col-md-5 col-lg-4 text-center">
                    <h5 class="mb-0">Total: <%= @order.total %> &euro;</h5>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="slice bg-gradient-primary">
    <span class="tongue tongue-top">
        <i class="fas fa-angle-up"></i>
    </span>
    <div class="container text-center">
        <h6 class="text-white">Checkout or return to shop to add more items</h6>
        <%= button_to "Go to Checkout", checkout_create_path, params: { amount: current_order.total }, class: 'btn btn-white btn-circle mt-4', remote: true %>
    </div>
</section>

app/views/carts/_empty_cart.html.erb
<section class="slice slice-xl h-100vh d-flex align-items-center">
    <div class="container pt-lg">
        <div class="row justify-content-center">
            <div class="col-lg-7">
                <div class="text-center">
                    <div class="icon icon-xl icon-shape icon-pink rounded-circle">
                        <i class="fas fa-shopping-cart"></i>
                    </div>
                    <h6 class="h4 my-4">Your cart is empty.</h6>
                    <p class="px-5">
                        Your cart is currently empty. Return to our shop and check out the latest offers. We have some great items that are waiting for you.
                    </p>
                    <%= link_to "Return to shop", root_path, class: 'btn btn-dark btn-circle mt-5'%>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/carts/show.html.erb
<% if @order_products.any? %>
    <%= render 'cart' %>
<% else %>
    <%= render 'empty_cart' %>
<% end %>

app/views/checkout/cancel.html.erb
<%= render partial: 'layouts/banner', locals: { page: 'Transaction cancelled', information: '' } %>
<p class="text-center mt-5">
	<strong>Your credit card has not been charged.</strong>
</p>

app/views/checkout/create.js.erb
const stripe = Stripe('<%= Rails.configuration.stripe[:publishable_key] %>');

stripe.redirectToCheckout({
	sessionId: '<%= @session.id %>'
}).then(function (result) {
	 console.log(result.error.message);
});

app/views/checkout/success.html.erb
<%= render partial: 'layouts/banner', locals: { page: 'Thank you!', information: '' } %>
<p class="text-center mt-5">
	<strong>You successfully purchased:</strong>
</p>

<table class="table text-center">
  <thead>
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Description</th>
      <th scope="col">Unit Price</th>
      <th scope="col">Quantity</th>
      <th scope="col">Total Price</th>
    </tr>
  </thead>
  <tbody>
  	<% @order_products.each do |order_product| %>
	    <tr>
	      <th scope="row"><%= order_product.product.title %></th>
	      <td><%= order_product.product.description %></td>
	      <td><%= order_product.product.price %></td>
	      <td><%= order_product.quantity %></td>
	      <td><%= order_product.total_price %></td>
	    </tr>
	  <% end %>
  </tbody>
</table>

app/views/home/_card.html.erb
<div class="col-lg-3 col-sm-6 mb-5">
    <div class="card card-product no-border shadow shadow--hover">
        <div class="card-image">    
        <%= link_to image_tag(product.image), product_path(product), alt: 'Image placeholder', class: 'img-center' %>
        
        </div>
        <div class="card-body pt-0 text-center">
            <%= link_to product.title, product, class: 'card-title' %>
            <span class="card-price"><%= product.price %> &euro;</span> 
        </div>
							
		<div class="container cart_icon">
            <%= form_with model: @order_product do |f| %>
				<%= f.hidden_field :product_id, value: product.id %>
				<%= f.button :submit, data: { toggle: 'tooltip', title: 'Add to cart' } do %>
                    <i class="fas fa-shopping-cart"></i>
                <% end %>
			<% end %>
		</div>

    </div>
</div>

app/views/home/_section.html.erb
<section class="slice" id="section_cat">
    <div class="container swiper-js-container">
        <div class="swiper-container"> 
            <div class="swiper-wrapper">
                <% @categories.each do |category| %>
                    <div class="swiper-slide">
                        <div class="text-center mt-3">
                            <%= link_to root_path(category: category, anchor: 'section_cat'), class: 'h6 font-weight-bolder' do %>
                                <%= image_tag "icons/clothing/#{category.name.singularize}.svg", height: 60, alt: category.name %>
                            <% end %>
                        </div>
                    </div>
                <% end %>
            </div>
            <div class="swiper-pagination"></div>
        </div>
    </div>
</section>

app/views/home/index.html.erb
<section class="slice slice-lg bg-cover bg-size--cover" style="background-image: url(<%= asset_path 'img-15.jpg' %>);">

    <div class="container py-lg">
        <div class="row">
            <div class="col-lg-5">
                <h2 class="h1 text-white">Fall Accessories</h2>
                <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                    <li class="breadcrumb-item">
                        <a href="#" class="text-normal">Home</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="#" class="text-normal">Shop</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="#" class="text-normal">Fitness clothing</a>
                    </li>
                </ol>
                <p class="lead text-white mt-4">There is only that moment and the incredible certainty that everything under the sun has been written by one hand only.</p>
                <a href="#section_products" class="btn btn-white btn-circle mt-4">Start shopping</a>
            </div>
        </div>
    </div>
    <div class="shape-container" data-shape-style="wavify" data-shape-position="bottom">
        <svg width="100%" height="100%" version="1.1" xmlns="http://www.w3.org/2000/svg" class="shape-fill-white" data-toggle="wavify">
            <defs></defs>
            <path d="" id="wave" class="shape-fill-white" />
        </svg>
    </div>

</section>

<%= render 'section' %>

<section class="slice slice-lg" id="sct-products">
    <div class="container" id="section_products">

        <div class="row">

		  <% @products.each do |product| %>
            <% cache product do %>
                <%= render partial: 'card', locals: { product: product }%>
            <% end %>
          <% end %>

        </div>

    </div>
</section>

app/views/home/orders.html.erb
<%= render partial: 'layouts/banner', locals: { page: 'Orders', information: 'Details' } %>

<div class="m-4">
	<% if @orders.any? %>
		<% @orders.each do |order| %>

			<strong><%= order.id %> - <%= order.created_at.strftime("%a, %b %d %Y at %I:%M%p") %></strong>
			<% order.products.each do |product| %>
				<div class="ml-4">
					<%= product.title %>
					<span class="text-secondary"><%= product.description %></span>
					<span class="text-primary"><%= product.price %></span>
				</div>
			<% end %>
			
		<% end %>
	<% else %>
		<h2 class="text-center">You have no order yet</h2>
	<% end %>
</div>