config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  root 'home#index'
  get 'orders', to: 'home#orders'

  namespace :admin do
    resources :dashboard, only: :index
    resources :products
    resources :categories
  end

  resources :products, only: :show
  
  scope '/checkout' do
  	post 'create', to: 'checkout#create', as: 'checkout_create'
  	get 'success', to: 'checkout#success', as: 'checkout_success'
  	get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  end

  resource :cart, only: :show
  resources :order_products, only: %i[create update destroy]

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  belongs_to :user
  has_many :order_products
  has_many :products, through: :order_products

  before_save :set_total

  def total
  	order_products.collect {|order_product| order_product.valid? ? (order_product.unit_price*order_product.quantity) : 0}.sum
  end

  def total_in_cent
  	(self.total*100).to_i
  end


  private

  def set_total
  	self[:total] = total
  end
end

app/models/order_product.rb
# frozen_string_literal: true

class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product

  before_save :set_unit_price
  before_save :set_total_price
  
  def unit_price
  	if persisted?
  		self[:unit_price]
  	else
  		product.price
  	end
  end

  def total_price
  	quantity * unit_price
  end


  private

  def set_unit_price
  	self[:unit_price] = unit_price
  end

  def set_total_price
  	self[:total_price] = quantity * set_unit_price
  end
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord

	before_validation :set_slug, on: [:create, :update]

  has_many :order_products
  has_many :orders, through: :order_products

  has_one_attached :image

  belongs_to :category

  validates_presence_of :slug

  def self.popular
 		ordered_products = Product.joins(:order_products).group(:id)
 		ordered_products_sum = ordered_products.sum(:quantity)
 		ordered_products_quantities = ordered_products_sum.map{|k,v| v}
 		ordered_products.enum_for(:each_with_index)
 			.map{|e,i|
 				{
 					title: e[:title],
 					price: e[:price],
 					quantity: ordered_products_quantities[i],
 					total: e[:price]*ordered_products_quantities[i]
 				}
 			}
 		.take(5)
  end

	def to_param
		slug
	end


	private

	def set_slug
		self.slug = title.parameterize
	end

end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :orders

  after_create :welcome_email

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def welcome_email
  	UserMailer.with(user: self).welcome_email.deliver_now
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
	before_action :set_category, only: [:show, :edit, :update, :destroy]

	def index
		@categories = Category.all
	end

	def show
	end

	def new
		@category = Category.new
	end

	def create
		@category = Category.create(category_params)
		if @category.save
			redirect_to admin_category_url(@category)
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @category.update(category_params)
			redirect_to admin_category_url(@category)
		else
			render 'edit'
		end
	end

	def destroy
		@category.destroy
		redirect_to admin_categories_path
	end


	private

	def set_category
		@category = Category.find(params[:id])
	end

	def category_params
		params.require(:category).permit(:name)
	end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  def index
  	@customers = User.where(admin: false).count
  	@orders = Order.where(paid: true)
  	@order_count = @orders.count
  	@revenue = @orders.pluck(:total)
  	@total_sales = @revenue.sum
  	@average_sale_size = 
  		@total_sales>0 ? @total_sales/@revenue.size : 0
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
	include Admin::ProductsHelper
	before_action :authenticate_admin
	before_action :set_product, only: [:show, :edit, :update, :destroy]

	def index
		@products = Product.includes(:category).all
	end

	def show
	end

	def new
		@product = Product.new
	end

	def create
		@product = Product.create(product_params)
		if @product.save
			redirect_to @product
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @product.update(product_params)
			redirect_to @product
		else
			render 'edit'
		end
	end

	def destroy
		@product.destroy
		redirect_to admin_products_path
	end


	private

	def set_product
		@product = Product.find_by_slug(params[:id])
	end

	def product_params
		params.require(:product).permit(:title, :description, :price, :image, :category_id)
	end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include ApplicationHelper
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

class CartsController < ApplicationController
  def show
  	@order = current_order
    @order_products = @order.order_products
  end
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  def create
  	order = current_order

  	@session = Stripe::Checkout::Session.create(
  		payment_method_types: ['card'],
  		line_items: [{
  			name: 'Eshop products',
  			description: "payment of order : #{order.id}",
  			amount: order.total_in_cent,
  			currency: 'eur',
  			quantity: 1,
			}],
      success_url: checkout_success_url,
      cancel_url: checkout_cancel_url,
  	)

  	respond_to do |format|
  		format.js
  	end
  end

  def success
    order = current_order
    order.update_attribute(:paid, true)
    @order_products = order.order_products
    cookies.delete(:cart)
    UserMailer.with(user: current_user).order_email.deliver_now
    UserMailer.with(admin: User.find_by(admin: true)).admin_order_email.deliver_now
  end

  def cancel
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @categories = Category.all
    category = params[:category]
    if !!category
    	@products = Product.where(category: category)
    else
    	@products = Product.all
    end
    @order_product = current_order.order_products.new
  end

  def orders
  	@orders = Order.where(user: current_user, paid: true).includes(:products)
  end
end

app/controllers/order_products_controller.rb
# frozen_string_literal: true

class OrderProductsController < ApplicationController
  before_action :set_order
  before_action :set_product, only: [:update, :destroy]
  
  def create
    @order_product = @order.order_products.new(order_item_params)
    @order.save
    cookies[:cart] = @order.id
  end

  def update
    @order_product.update_attributes(order_item_params)
    redirect_to cart_path
  end

  def destroy
    @order_product.destroy
    redirect_to cart_path
  end

  private

  def set_order
    @order = current_order
  end

  def set_product
    @order_product = @order.order_products.find(params[:id])
  end

  def order_item_params
    params.require(:order_product).permit(:product_id, :quantity)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def show
  	@product = Product.find_by_slug(params[:id])
  	@products = Product.all.sample(4)
  	@order_product = current_order.order_products.new
  end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
	def authenticate_admin
		redirect_to root_path if !current_user.admin
	end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def current_order
    if !!cookies[:cart]
      Order.find(cookies[:cart])
    else
      Order.new(user: current_user)
    end
  end
end

app/helpers/carts_helper.rb
# frozen_string_literal: true

module CartsHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/order_products_helper.rb
# frozen_string_literal: true

module OrderProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= form_with model: [:admin, product], local: true do |form| %>

	<% if @product.errors.any? %>
	    <div id="error_explanation">
	      <h2>
	        <%= pluralize(@product.errors.count, "error") %> prohibited
	        this product from being saved:
	      </h2>
	      <ul>
	        <% @product.errors.full_messages.each do |msg| %>
	          <li><%= msg %></li>
	        <% end %>
	      </ul>
	    </div>
	<% end %>

	<p>
		<%= form.label :title %>
		<%= form.text_field :title %>
	</p>

	<p>
		<%= form.label :description %>
		<%= form.text_area :description %>
	</p>

	<p>
		<%= form.label :price %>
		<%= form.number_field :price, in: 0.00..999.99, step: 0.01 %>
	</p>

	<p>
		<%= form.file_field :image %>
	</p>

	<p>
		<%= form.select :category_id, Category.all.map{|c| [c.name, c.id]} %>
	</p>
	
	<p>
		<%= form.submit %>
	</p>

<% end %>

app/views/admin/products/edit.html.erb
<%= render partial: 'layouts/banner', locals: { page: 'Edit Product', information: '' } %>

<div class="container mt-3">

	<%= render partial: 'form', locals: { product: @product } %>

	<%= link_to 'Back', admin_products_path %>
</div>

app/views/admin/products/index.html.erb
<%= render partial: 'layouts/banner', locals: { page: 'Listing Products', information: '' } %>

<div class="container mt-3">

	<%= link_to '<i class="fa fa-plus"></i>'.html_safe, new_admin_product_path %>

	<table class="table-responsive">
		<tr>
			<th scope="col">Title</th>
			<th scope="col">Description</th>
			<th scope="col">Price</th>
			<th scope="col">Category</th>
			<th scope="col" colspan="3">Actions</th>
		</tr>

		<%@products.each do |product| %>
			<tr>
	      <td><%= product.title %></td>
	      <td><%= product.description %></td>
	      <td><%= product.price %></td>
	      <td><%= product.category.name %></td>
	      <td><%= link_to '<i class="fa fa-eye"></i>'.html_safe, admin_product_path(product), class: 'btn btn-primary' %></td>
	      <td><%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_admin_product_path(product), class: 'btn btn-warning' %></td>
	      <td><%= link_to '<i class="fa fa-trash"></i>'.html_safe, admin_product_path(product), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
	    </tr>
		<% end %>
	</table>

	<%= link_to 'Back', admin_dashboard_index_path %>
</div>

app/views/admin/products/new.html.erb
<%= render partial: 'layouts/banner', locals: { page: 'New Product', information: '' } %>

<div class="container mt-3">

	<%= render partial: 'form', locals: { product: @product } %>

	<%= link_to 'Back', admin_products_path %>
</div>

app/views/admin/products/show.html.erb
<%= render partial: 'layouts/banner', locals: { page: 'Product', information: '' } %>

<div class="container mt-3">
	<p>
		<strong>Title:</strong>
		<%= @product.title %>
	</p>
	<p>
		<strong>Description:</strong>
		<%= @product.description %>
	</p>
	<p>
		<strong>Price:</strong>
		<%= @product.price %>
	</p>

	<% if @product.image.attached? %>
		<%= image_tag @product.image, alt: 'image' %>
	<% else %>
		<p>=== Il n'y a pas encore d'image lié à ce produit ===</p>
	<% end %>

	<%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_admin_product_path(@product) %> |
	<%= link_to 'Back', admin_products_path %>
</div>

app/views/products/show.html.erb
<header class="slice pt-lg pb-4 bg-gradient-warning d-flex align-items-end">
    <div class="container pt-lg">
        <div class="row">
            <div class=" col-lg-12">
                <div class="row align-items-center mb-4">
                    <div class="col-lg-5 mb-4 mb-lg-0">
                        <span class="h2 mb-0 text-white d-block"><%= @product.title %></span>
                        <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                            <li class="breadcrumb-item">
                                <a href="#" class="text-normal">Home</a>
                            </li>
                            <li class="breadcrumb-item">
                                <a href="#" class="text-normal">Shop</a>
                            </li>
                            <li class="breadcrumb-item">
                                <a href="#" class="text-normal"><%= @product.category.name %></a>
                            </li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

<section class="slice slice-lg" id="sct-products">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <!-- Product gallery -->
                <div class="mb-5">
                    <%= image_tag @product.image, alt:"Image placeholder", class: 'img-fluid rounded shadow shadow-lg--hover' %>
                </div>

            </div>
            <div class="col-lg-6">
                <div class="pl-lg-4">
                    <!-- Product title -->
                    <h2 class="h5 text-capitalize"><%= @product.title %></h2>

                    <!-- Rating stars -->

                    <span class="static-rating static-rating-sm">

                        <i class="star fas fa-star voted"></i>
                        <i class="star fas fa-star voted"></i>
                        <i class="star fas fa-star voted"></i>
                        <i class="star fas fa-star voted"></i>
                        <i class="star fas fa-star"></i>
                        
                    </span>


                    <!-- Product description -->
                    <div class="mt-4">
                        <small class="text-dark font-weight-bold d-block mb-2">Description:</small>
                        <p class="text-sm lh-150"><%= @product.description %></p>
                    </div>


                    <!-- Quantity -->
                    <div class="mt-4">
                        <small class="d-block font-weight-bold text-dark mb-2">Quantity</small>
                        <div class="d-flex">
                            <%= form_with model: @order_product do |f| %>
                                <div class="row">
                                    <%= f.hidden_field :product_id, value: @product.id %>
                                    <%= f.text_field :quantity, min: 1, placeholder: 'Qty', class: 'form-control text-center ml-3', style: 'width: 100px' %>
                                    <%= f.submit 'Add to cart', class: 'btn btn-primary ml-3' %>
                                </div>
                            <% end %>
                        </div>

                    </div>

                    <!-- Product info -->
                    <div class="mt-4">
                        <small class="d-block font-weight-bold text-dark">Maintaining</small>
                        <ul class="list-unstyled list-icon">
                            <li class="text-sm py-1">
                                <i class="fas fa-tshirt mr-3"></i>Exterior: 98% cotton, 2% elastane
                            </li>
                            <li class="text-sm py-1">
                                <i class="fas fa-air-freshener mr-3"></i>Machine wash up to 30&deg;/86&deg;F gentle cycle
                            </li>
                            <li class="text-sm py-1">
                                <i class="fas fa-charging-station mr-3"></i>Iron up to 110&deg;C/230&deg;F
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="slice slice-lg delimiter-top" id="sct-suggested-products">
    <div class="container">
        <div class="mb-md text-center">
            <h5>Suggested products</h5>
            <div class="fluid-paragraph text-center mt-2">
                <p class="lead lh-180">Check out these special products that we think you might like</p>
            </div>
        </div>

        <div class="row">
            <% @products.each do |product| %>
                <%= render partial: 'home/card', locals: { product: product } %>
            <% end %>
        </div>
    </div>
</section>